pipeline:
  install:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm ci
  build:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm run build
  lint:js:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm run lint:js
  lint:hbs:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm run lint:hbs
  lint:css:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm run lint:css
  lint:dependencies:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - ember dependency-lint
  test:
    image: danlynn/ember-cli:5.8.0-node_20.12
    commands:
      - npm run test:ember
